base_local_planner: nav_core_adapter::LocalPlannerAdapter
LocalPlannerAdapter:
  planner_name: dwb_local_planner::DWBLocalPlanner
DWBLocalPlanner:
    min_vel_x: 0.01
    max_vel_x: 0.1

    max_rot_vel: 0.1
    # min_in_place_vel_theta: 0.05

    acc_lim_theta: 1.0
    acc_lim_x: 1.0
    acc_lim_y: 0.0

    publish_evaluation: true

    sim_time: 1.0

robot_radius: 0.175
