TrajectoryPlannerROS:
    max_vel_x: 0.1
    min_vel_x: 0.01
    min_vel_theta: -0.1
    max_vel_theta: 0.1
    min_in_place_vel_theta: 0.05

    acc_lim_theta: 1.0
    acc_lim_x: 1.0
    acc_lim_y: 0.0
    publish_cost_grid_pc: true

    holonomic_robot: false
    sim_time: 3.0
