obstacle_layer:
    obstacle_range: 2.5
    raytrace_range: 3.0

    observation_sources: laser_scan_sensor

    laser_scan_sensor:
        sensor_frame: laser
        data_type: LaserScan
        topic: scan_filtered
        marking: true
        clearing: true

inflation_layer:
    inflation_radius: 0.55
